[package]
name = "murmer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A distributed actor framework for Rust"
keywords = ["actor", "distributed", "async", "network"]
categories = ["asynchronous", "network-programming", "concurrency"]

[dependencies]
futures = "0.3.31"
parking_lot = "0.12.3"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.13.1", features = ["v4", "serde"] }
