[workspace]
members = [
    "murmer"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Andrew Paxson <andrew.paxson@icloud.com>"]
keywords = ["actor", "distributed", "actor-model", "async"]
license = "MIT or Apache-2.0"

